<?php

########################################################################
# Extension Manager/Repository config file for ext: "jquery_ui"
#
# Auto generated by Extension Builder 2011-12-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'jQuery UI Fluid ViewHelpers',
	'description' => 'Provides jQuery UI Fluid ViewHelpers.',
	'category' => 'plugin',
	'author' => 'Martin Helmich',
	'author_email' => 'typo3@martin-helmich.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>